//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchWebApp_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChurchAnalytics : DbContext
    {
        public ChurchAnalytics()
            : base("name=ChurchAnalytics")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_city> tbl_city { get; set; }
        public virtual DbSet<tbl_country> tbl_country { get; set; }
        public virtual DbSet<tbl_department> tbl_department { get; set; }
        public virtual DbSet<tbl_department_member_position> tbl_department_member_position { get; set; }
        public virtual DbSet<tbl_hierarchy_description> tbl_hierarchy_description { get; set; }
        public virtual DbSet<tbl_hy1> tbl_hy1 { get; set; }
        public virtual DbSet<tbl_hy2> tbl_hy2 { get; set; }
        public virtual DbSet<tbl_hy3> tbl_hy3 { get; set; }
        public virtual DbSet<tbl_hy4> tbl_hy4 { get; set; }
        public virtual DbSet<tbl_hy5> tbl_hy5 { get; set; }
        public virtual DbSet<tbl_member_biodata> tbl_member_biodata { get; set; }
        public virtual DbSet<tbl_organization> tbl_organization { get; set; }
        public virtual DbSet<tbl_position> tbl_position { get; set; }
        public virtual DbSet<tbl_state> tbl_state { get; set; }
    }
}
