//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchWebApp_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hy5
    {
        public int id { get; set; }
        public int tbl_hy4_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public int leaders_id { get; set; }
    
        public virtual tbl_hy4 tbl_hy4 { get; set; }
        public virtual tbl_member_biodata tbl_member_biodata { get; set; }
    }
}
