//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchWebApp_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member_biodata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_member_biodata()
        {
            this.tbl_department_member_position = new HashSet<tbl_department_member_position>();
            this.tbl_hy1 = new HashSet<tbl_hy1>();
            this.tbl_hy2 = new HashSet<tbl_hy2>();
            this.tbl_hy3 = new HashSet<tbl_hy3>();
            this.tbl_hy4 = new HashSet<tbl_hy4>();
            this.tbl_hy5 = new HashSet<tbl_hy5>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime dob { get; set; }
        public string phone_number { get; set; }
        public string house_address { get; set; }
        public byte[] photo { get; set; }
        public string marital_status { get; set; }
        public Nullable<int> house_fellowship_id { get; set; }
        public Nullable<System.DateTime> date_of_initial_attendant { get; set; }
        public string gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_department_member_position> tbl_department_member_position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hy1> tbl_hy1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hy2> tbl_hy2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hy3> tbl_hy3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hy4> tbl_hy4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hy5> tbl_hy5 { get; set; }
    }
}
