//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchWebApp_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_organization
    {
        public int id { get; set; }
        public string organization_name { get; set; }
        public string organization_address { get; set; }
        public string organization_state { get; set; }
        public string organization_city { get; set; }
        public int country_id { get; set; }
        public string orgdiscription { get; set; }
    
        public virtual tbl_country tbl_country { get; set; }
    }
}
